---
- name: ESXi Info 
  hosts: ansible_host
  vcenter_server: 172.20.1.220
  vcenter_username: administrator@vsphere.local
  vcenter_password: Cbi@202104*
     tasks:
    - name: Gather product version info for ESXi from vCenter
      community.vmware.vmware_host_facts:
          hostname: "{{ vcenter_server }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          properties:
            - config.product
            - config.option
            - runtime.connectionState
            - runtime.powerState
            - hardware.memorySize
            - hardware.cpuInfo.numCpuCores
            - config.product.apiVersion
            - overallStatus
