---
- name: ESXi Reboot with MM #vmcloud.pl
  hosts: localhost
  gather_facts: no

  vars:
    vcenter_server: "vCenter_IP_or_hostname"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "pw"
    esxi_hostname: "ESXi_hostname"

  tasks:
    - name: Enter ESXi Maintenance Mode
      register: status
      community.vmware.vmware_maintenancemode:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        validate_certs: no
        evacuate: false   #Value true will migrate Powered Off VMs to other host
        timeout: 3600     #Timeout for the operation (sec)
        state: present

    - debug: var=status.msg

    - name: ESXi reboot 
      vmware_host_powerstate: 
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        validate_certs: no
        timeout: 3600   #Timeout for the operation (sec)
        state: reboot-host
      register: reboot_host
  
    - name: ESXi wait for the reboot to complete
      wait_for:
        host: "{{ esxi_hostname }}"
        port: 443
        delay: 600        #Perform first check after delay (sec)
        state: started
        timeout: 3600     #Timeout for the operation (sec)

    - name: Exit ESXi Maintenance Mode
      register: status
      community.vmware.vmware_maintenancemode:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        validate_certs: no
        timeout: 3600     #Timeout for the operation (sec)
        state: absent

    - debug: var=status.msg
