---
- name: Exit MM on ESXi host #vmcloud.pl
  hosts: localhost
  gather_facts: no

  vars:
    vcenter_server: "vCenter_IP_or_hostname"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "pw"
    esxi_hostname: "ESXi_hostname"

  tasks:
    - name: Exit ESXi Maintenance Mode
      register: status
      community.vmware.vmware_maintenancemode:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        validate_certs: no
        timeout: 3600     #Timeout for the operation (sec)
        state: absent

    - debug: var=status.msg
